### ISSUE TITLE
Update signature for script

### ISSUE THREAD

**Issue by Spicy-Toaster** [v-bldrum/SCOM-Scripts-and-SQL#9]
This scripts signature expired last year. Any chance it can be renewed?
https://github.com/blakedrumm/SCOM-Scripts-and-SQL/blob/master/Powershell/General%20Functions/Get-UserRights.ps1

**Comment by blakedrumm** [comment]
> This scripts signature expired last year. Any chance it can be renewed?
> 
> https://github.com/blakedrumm/SCOM-Scripts-and-SQL/blob/master/Powershell/General%20Functions/Get-UserRights.ps1

Working on it, thank you for letting me know! 🙂

**Comment by blakedrumm** [comment]
The digital signatures have been renewed [https://github.com/blakedrumm/SCOM-Scripts-and-SQL/commit/cfaafdf356c3c69db0e63fc1d95b2d54b3456169](https://github.com/blakedrumm/SCOM-Scripts-and-SQL/commit/cfaafdf356c3c69db0e63fc1d95b2d54b3456169)
